# 1. Importación de librerías

In [67]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Carga del dataset
df = pd.read_csv("../data/supermarket_sales.csv")

# 2. Comprobamos que datos hay en el dataset

In [68]:
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A1,Yangon,Member,Female,Health and beauty,92,9,33,691,5/1/2019,13:08,Ewallet,635,5,31,11
1,226-31-3081,C1,Naypyitaw,Normal,Female,Electronic accessories,18,6,4,101,8/3/2019,10:29,Cash,92,5,4,12
2,631-41-3108,A1,Yangon,Normal,Male,Home and lifestyle,57,9,20,429,3/3/2019,13:23,Credit card,394,5,19,9
3,123-19-1176,A1,Yangon,Member,Male,Health and beauty,72,10,29,616,27/1/2019,20:33,Ewallet,566,5,28,10
4,373-73-7910,A1,Yangon,Normal,Male,Sports and travel,106,9,38,799,8/2/2019,10:37,Ewallet,734,5,36,6

## Reviso si hay duplicados

In [69]:
df.duplicated().sum()

np.int64(0)

## Reviso si "Invoice ID" es tipo string o número y vuelvo a confirmar que no hay duplicados. Va a ser mi varible categorica.

In [70]:
df["Invoice ID"].dtype

In [71]:
df["Invoice ID"].duplicated().sum()

np.int64(0)

### **Exploración inicial de variables categóricas**

Se identifican las columnas de tipo texto y se contabilizan sus valores distintos mediante `nunique()`, que excluye los valores nulos por defecto.

En esta primera exploración se observan 89 fechas diferentes, 3 ciudades, 1.400 identificadores de factura distintos y 6 líneas de producto.

Estos resultados permiten conocer la diversidad de los datos antes de comenzar el análisis exploratorio.

In [72]:
df.select_dtypes(include=["string", "object"])
df.select_dtypes(include=["string", "object"]).nunique()

Invoice ID       1400
Branch              7
City                3
Customer type       2
Gender              2
Product line        6
Date               89
Time              506
Payment             3
dtype: int64

In [73]:
df["Date"].dtype

In [74]:
display(df["Date"].head(10))

0     5/1/2019
1     8/3/2019
2     3/3/2019
3    27/1/2019
4     8/2/2019
5    25/3/2019
6    25/2/2019
7    24/2/2019
8    10/1/2019
9    20/2/2019
Name: Date, dtype: str

In [75]:
df["Date"] = pd.to_datetime(df["Date"], format="%d/%m/%Y")
print(df["Date"].dtype)

print("Primera fecha:", df["Date"].min().strftime("%d/%m/%y"))
print("Última fecha:", df["Date"].max().strftime("%d/%m/%y"))

datetime64[us]
Primera fecha: 01/01/19
Última fecha: 30/03/19

In [76]:
display(df.sort_values(by="Date").head(10))
display(df.sort_values(by="Invoice ID").head(10))

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
970,746-04-1077,B1,Mandalay,Member,Female,Food and beverages,104,12,53,1119,2019-01-01,11:36,Credit card,1028,5,51,11
1012,272-95-2897,A1,Yangon,Member,Female,Home and lifestyle,566,41,932,19383,2019-01-01,16:30,Ewallet,17811,6,1702,2
839,271-77-8740,C1,Naypyitaw,Member,Female,Sports and travel,36,7,11,231,2019-01-01,11:40,Ewallet,213,5,10,6
496,556-97-7101,C1,Naypyitaw,Normal,Female,Electronic accessories,78,2,8,167,2019-01-01,15:51,Cash,153,5,7,10
484,493-65-6248,C1,Naypyitaw,Member,Female,Sports and travel,45,12,23,489,2019-01-01,19:48,Credit card,449,5,22,9
1203,588-83-6291,A3,Naypyitaw,Normal,Male,Fashion accessories,818,23,758,15756,2019-01-01,15:15,Cash,14479,22,2252,3
1014,312-87-6090,C3,Yangon,Normal,Male,Home and lifestyle,4,58,11,230,2019-01-01,15:08,Ewallet,211,8,11,9
450,891-01-7034,B1,Mandalay,Normal,Female,Electronic accessories,92,7,28,592,2019-01-01,19:07,Cash,544,5,27,8
17,765-26-6951,A1,Yangon,Normal,Male,Sports and travel,89,7,27,576,2019-01-01,10:39,Credit card,529,5,26,8
523,133-14-7229,C1,Naypyitaw,Normal,Male,Health and beauty,77,2,8,166,2019-01-01,11:43,Cash,152,5,7,6

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
162,101-17-6199,A1,Yangon,Normal,Male,Food and beverages,56,9,20,424,2019-03-13,19:44,Credit card,389,5,19,9
867,101-81-4070,C1,Naypyitaw,Member,Female,Health and beauty,77,2,7,166,2019-01-17,12:36,Ewallet,152,5,7,6
778,102-06-2002,C1,Naypyitaw,Member,Male,Sports and travel,31,6,8,167,2019-03-20,17:52,Cash,153,5,7,7
776,102-77-2261,C1,Naypyitaw,Member,Male,Health and beauty,80,9,29,604,2019-03-05,18:02,Credit card,555,5,27,5
683,105-10-6182,A1,Yangon,Member,Male,Fashion accessories,26,2,2,56,2019-02-27,12:22,Ewallet,52,5,2,8
169,105-31-1824,A1,Yangon,Member,Male,Sports and travel,86,9,30,643,2019-02-01,15:10,Credit card,591,5,29,10
56,106-35-6779,A1,Yangon,Member,Male,Home and lifestyle,54,2,5,117,2019-03-27,11:26,Cash,107,5,5,7
1314,106-39-2931,B1,Mandalay,Member,Male,Electronic accessories,770,32,991,20598,2019-01-15,20:24,Ewallet,18928,5,2464,5
67,109-28-2512,B1,Mandalay,Member,Female,Fashion accessories,120,7,37,774,2019-01-07,15:01,Ewallet,711,5,35,12
1237,109-43-1373,C1,Naypyitaw,Member,Male,Food and beverages,688,102,2799,58167,2019-03-02,11:45,Ewallet,53451,17,9100,4

### Buscamos los valores nulos o ausentes

In [77]:
print("VALORES NULOS")
display(df.isna().sum())

print("CADENAS VACÍAS")
display((df == "").sum())

print("CELDAS CON UN ESPACIO")
display((df == " ").sum())

VALORES NULOS

Invoice ID                 0
Branch                     0
City                       0
Customer type              0
Gender                     0
Product line               0
Unit price                 0
Quantity                   0
Tax 5%                     0
Total                      0
Date                       0
Time                       0
Payment                    0
cogs                       0
gross margin percentage    0
gross income               0
Rating                     0
dtype: int64

CADENAS VACÍAS

Invoice ID                 0
Branch                     0
City                       0
Customer type              0
Gender                     0
Product line               0
Unit price                 0
Quantity                   0
Tax 5%                     0
Total                      0
Date                       0
Time                       0
Payment                    0
cogs                       0
gross margin percentage    0
gross income               0
Rating                     0
dtype: int64

CELDAS CON UN ESPACIO

Invoice ID                 0
Branch                     0
City                       0
Customer type              0
Gender                     0
Product line               0
Unit price                 0
Quantity                   0
Tax 5%                     0
Total                      0
Date                       0
Time                       0
Payment                    0
cogs                       0
gross margin percentage    0
gross income               0
Rating                     0
dtype: int64

# 3. Consistencia de variables categóricas 
    Revisamos todas las columnas que son cadenas de texto

In [78]:
columnas = [
    "Gender",
    "Branch",
    "City",
    "Customer type",
    "Product line",
    "Payment"
]

for columna in columnas:
    print(f"\n--- {columna} ---")
    display(df[columna].value_counts(dropna=False))

--- Gender ---

Gender
Male      713
Female    687
Name: count, dtype: int64

--- Branch ---

Branch
A1    393
C1    371
B1    367
A3     89
B2     82
C2     50
C3     48
Name: count, dtype: int64

--- City ---

City
Yangon       475
Naypyitaw    463
Mandalay     462
Name: count, dtype: int64

--- Customer type ---

Customer type
Member    725
Normal    675
Name: count, dtype: int64

--- Product line ---

Product line
Fashion accessories       248
Electronic accessories    247
Food and beverages        242
Home and lifestyle        231
Sports and travel         230
Health and beauty         202
Name: count, dtype: int64

--- Payment ---

Payment
Cash           503
Ewallet        477
Credit card    420
Name: count, dtype: int64

## Validación y limpieza de datos

Se han realizado las siguientes comprobaciones de calidad:

- **Valores nulos:** no se han detectado valores ausentes mediante `isna()`.
- **Cadenas vacías:** no se han encontrado celdas vacías (`""`) ni celdas que contengan exactamente un espacio (`" "`).
- **Duplicados:** no existen filas completamente duplicadas ni identificadores de factura (`Invoice ID`) repetidos.
- **Consistencia categórica:** se han revisado las columnas `Gender`, `Branch`, `City`, `Customer type`, `Product line` y `Payment` mediante `value_counts()`. No se han observado inconsistencias evidentes en sus categorías.
- **Fechas:** se ha convertido la columna `Date` de texto a tipo `datetime`, utilizando el formato original día/mes/año.

**Conclusión provisional:** los datos presentan una buena calidad inicial. No ha sido necesario eliminar registros ni corregir las categorías revisadas.

**Pendiente:** comprobar la coherencia de los valores numéricos, detectar posibles valores atípicos y validar las relaciones entre variables.

# 4 Análisis de consistencia de variables numéricas

In [80]:
display(df.describe().round(2))

,Unit price,Quantity,Tax 5%,Total,Date,cogs,gross margin percentage,gross income,Rating
count,1400.00,1400.00,1400.00,1400.00,1400,1400.00,1400.00,1400.00,1400.00
mean,185.44,18.16,310.22,6456.19,2019-02-14 06:14:24,5932.66,6.04,651.97,7.76
min,1.00,1.00,0.00,13.00,2019-01-01 00:00:00,12.00,0.00,0.00,0.00
25%,49.00,5.00,10.00,211.00,2019-01-24 18:00:00,194.00,5.00,9.00,6.00
50%,88.00,9.00,24.00,509.00,2019-02-13 00:00:00,468.00,5.00,23.00,8.00
75%,123.00,14.00,91.25,1913.00,2019-03-09 00:00:00,1757.75,5.00,112.00,10.00
max,1224.00,126.00,5992.00,124531.00,2019-03-30 00:00:00,114434.00,24.00,20899.00,12.00
std,255.13,24.81,807.43,16778.29,NaN,15417.90,3.61,2110.92,2.92

In [82]:
(df["Quantity"] > 50).sum()

np.int64(156)

In [85]:
porcentaje = (df["Quantity"] > 50).sum() / len(df) * 100
print(round(porcentaje, 2), "% de las compras tienen una cantidad mayor a 50 unidades.")

11.14 % de las compras tienen una cantidad mayor a 50 unidades.